permalink: /:categories/:title/
markdown: kramdown
url: "http://codeforsanfrancisco.org"

owner:
  twitter: sfbrigade

prose:
  media: 'media'
  rooturl: '_posts'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /js
  metadata:
    _posts/blog:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "author"
        field:
          element: "select"
          label: "Author"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          alterable: true
          placeholder: "Choose Tags"
          options: "http://codeforsanfrancisco.org/api/authors.json"

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
